version: '3.9'

services:

  app:
    container_name: fastapi_container
    build:
      context: .
    env_file:
      - .env-docker
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
      - redis

  db:
    container_name: postgres_container
    image: postgres:alpine
    env_file:
      - .env-docker
    ports:
      - '5435:5432'
    restart: always

  redis:
    container_name: redis_container
    image: redis:alpine
    env_file:
      - .env-docker
    ports:
      - '6385:6379'
    restart: always