version: '3.9'

services:

  db_test:
    container_name: postgres_container_test
    image: postgres:alpine
    env_file:
      - .env-docker
    ports:
      - '5434:5432'
    restart: always

  redis_test:
    container_name: redis_container_test
    image: redis:alpine
    env_file:
      - .env-docker
    ports:
      - '6384:6379'
    restart: always